version: '3.8'

services:
  spring-boot-app:
    image: springapp
    container_name: spring-boot-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/DBName
      - SPRING_DATASOURCE_USERNAME=UNAME
      - SPRING_DATASOURCE_PASSWORD=PWD
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: YOURPWD
      MYSQL_DATABASE: DBNAME
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
